### ISSUE TITLE
Question: quelle version 6 ou 7?

### ISSUE THREAD

**Issue by michelekorell** [dgm01/TOS_GIT#1]
Bonjour,

Vous avez effectué l'installation du plugin egit dans la version 6 ou 7?
J'ai essayé dans la 7.3 avec environnement macos et ça ne détecte pas les plugins.

merci d'avance et bonne journée!

Michele

**Comment by dgm01** [comment]
Salut Michele

Je pense bien que c'était avec TOS 7
Je vérifie ça pendant ma pause et je te fais signe si le besoin 

Maurice

**Comment by michelekorell** [comment]
Bonjour, merci de la réponse rapide ! 

Désolé, j'ai mis un moment à répondre, mon emploi du temps est un peu surchargé dernièrement suite à la situation extraordinaire qu’on passe. J’ai essayé à nouveau à mettre ces plugins mais vraiment Talend ne veut pas les charger. Peut-être c’est car je travaille sur mac OSX. Le guide dans le lien parle de la version 6 sous Windows. Je vais ressayer avec la vieille version et sous Windows.

Merci et bonne journée !

**Comment by dorel14** [comment]
la même chose pour moi en 7.3 sur windows, pas de fenetre git affichée
